CRMApp/Antra.CRMApp.WebMVC/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Antra.CRMApp.WebMVC.Models;
using Antra.CRMApp.Core.Contract.Service;
using Antra.CRMApp.Core.Model;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Antra.CRMApp.WebMVC.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductServiceAsync productServiceAsync;
        private readonly IVendorServiceAsync vendorServiceAsync;
        private readonly ICategoryServiceAsync categoryServiceAsync;
        public ProductController(IProductServiceAsync productservice, IVendorServiceAsync vendorservice, ICategoryServiceAsync categoryservice)
        {
            productServiceAsync = productservice;
            vendorServiceAsync = vendorservice;
            categoryServiceAsync = categoryservice;
        }
        public async Task<IActionResult> Index()
        {
            var productCollection = await productServiceAsync.AllAsync;
            if (productCollection != null)
                return View(productCollection);

            List<ProductResponseModel> model = new List<ProductResponseModel>();
            return View(model);
        }
        public IActionResult Detail()
        {
            ViewData["Title"] = "Product/Details";
            return View("explain");
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var collection1 = await vendorServiceAsync.GetAllAsync();
            ViewBag.Vendors = new SelectList(collection1, "Id", "Name");
            var collection2 = await categoryServiceAsync.GetAllAsync();
            ViewBag.Categories = new SelectList(collection2, "Id", "Name");
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(ProductRequestModel model)
        {
            if (ModelState.IsValid)
            {
                await productServiceAsync.AddProductAsync(model);
                return RedirectToAction("Index");
            }
            var collection1 = await vendorServiceAsync.GetAllAsync();
            ViewBag.Vendors = new SelectList(collection1, "Id", "Name");
            var collection2 = await categoryServiceAsync.GetAllAsync();
            ViewBag.Categories = new SelectList(collection2, "Id", "Name");
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            ViewBag.IsEdit = false;
            var proModel = await productServiceAsync.GetProductForEditAsync(id);
            var collection1 = await vendorServiceAsync.GetAllAsync();
            ViewBag.Vendors = new SelectList(collection1, "Id", "Name");
            var collection2 = await categoryServiceAsync.GetAllAsync();
            ViewBag.Categories = new SelectList(collection2, "Id", "Name");
            return View(proModel);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(ProductRequestModel model)
        {
            ViewBag.IsEdit = false;
            var collection1 = await vendorServiceAsync.GetAllAsync();
            ViewBag.Vendors = new SelectList(collection1, "Id", "Name");
            var collection2 = await categoryServiceAsync.GetAllAsync();
            ViewBag.Categories = new SelectList(collection2, "Id", "Name");
            if (ModelState.IsValid)
            {
                await productServiceAsync.UpdateProductAsync(model);
                ViewBag.IsEdit = true;
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            await productServiceAsync.DeleteProductAsync(id);
            return RedirectToAction("Index");
        }
    }
}

CRMApp/Antra.CRMApp.WebMVC/Controllers/RegionController.cs
using Antra.CRMApp.Core.Contract.Service;
using Antra.CRMApp.Core.Model;
using Microsoft.AspNetCore.Mvc;

namespace Antra.CRMApp.WebMVC.Controllers
{
    public class RegionController : Controller
    {
        private readonly IRegionServiceAsync regionServiceAsync;
        public RegionController(IRegionServiceAsync reg)
        {
            regionServiceAsync = reg;
        }
        public async Task<IActionResult> Index()
        {
            var result = await regionServiceAsync.GetAllAsync();
            return View(result);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(RegionModel model)
        {
            if (ModelState.IsValid)
            {
                await regionServiceAsync.AddRegionAsync(model);
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            ViewBag.IsEdit = false;
            var regModel = await regionServiceAsync.GetRegionForEditAsync(id);
            return View(regModel);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(RegionModel model)
        {
            ViewBag.IsEdit = false;
            if (ModelState.IsValid)
            {
                await regionServiceAsync.UpdateRegionAsync(model);
                ViewBag.IsEdit = true;
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            await regionServiceAsync.DeleteRegionAsync(id);
            return RedirectToAction("Index");
        }
    }
}

CRMApp/Antra.CRMApp.WebMVC/Controllers/ShipperController.cs
using Antra.CRMApp.Core.Contract.Service;
using Antra.CRMApp.Core.Model;
using Microsoft.AspNetCore.Mvc;

namespace Antra.CRMApp.WebMVC.Controllers
{
    public class ShipperController : Controller
    {
        private readonly IShipperServiceAsync shipperServiceAsync;
        public ShipperController(IShipperServiceAsync shipperServiceAsync)
        {
            this.shipperServiceAsync = shipperServiceAsync;
        }

        public async Task<IActionResult> Index()
        {
            var shipperCollection = await shipperServiceAsync.GetAllAsync();
            if (shipperCollection != null)
            {
                return View(shipperCollection);
            }
            List<ShipperModel> shipper = new List<ShipperModel>();
            return View(shipper);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(ShipperModel model)
        {
            if (ModelState.IsValid)
            {
                await shipperServiceAsync.AddShipperAsync(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            ViewBag.IsEdit = false;
            var shipperModel = await shipperServiceAsync.GetShipperForEditAsync(id);
            return View(shipperModel);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(ShipperModel model)
        {
            ViewBag.IsEdit = false;
            if (ModelState.IsValid)
            {
                await shipperServiceAsync.UpdateShipperAsync(model);
                ViewBag.IsEdit = true;
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            await shipperServiceAsync.DeleteShipperAsync(id);
            return RedirectToAction("Index");
        }
    }
}

CRMApp/Antra.CRMApp.WebMVC/Controllers/VendorController.cs
using Antra.CRMApp.Core.Contract.Service;
using Antra.CRMApp.Core.Model;
using Microsoft.AspNetCore.Mvc;

namespace Antra.CRMApp.WebMVC.Controllers
{
    public class VendorController : Controller
    {
        private readonly IVendorServiceAsync vendorServiceAsync;
        public VendorController(IVendorServiceAsync vendorservice)
        {
            vendorServiceAsync = vendorservice;
        }
        public async Task<IActionResult> Index()
        {
            var venCollection = await vendorServiceAsync.GetAllAsync();
            if (venCollection != null)
                return View(venCollection);

            List<VendorResponseModel> model = new List<VendorResponseModel>();
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(VendorRequestModel model)
        {
            if (ModelState.IsValid)
            {
                await vendorServiceAsync.AddVendorAsync(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            ViewBag.IsEdit = false;
            var venModel = await vendorServiceAsync.GetVendorForEditAsync(id);
            return View(venModel);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(VendorRequestModel model)
        {
            ViewBag.IsEdit = false;
            if (ModelState.IsValid)
            {
                await vendorServiceAsync.UpdateVendorAsync(model);
                ViewBag.IsEdit = true;
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            await vendorServiceAsync.DeleteVendorAsync(id);
            return RedirectToAction("Index");
        }
    }
}

CRMApp/Antra.CRMApp.WebMVC/Views/Shared/_CategoryRow.cshtml
@model CategoryModel
<tr>
    <td>@Model.Id</td>
    <td>@Model.Name</td>
    <td>@Model.Description</td>
    <td>
        <span>
            <a asp-controller="Category" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>
        </span>
    </td>
    <td>
        <span>
            <a asp-controller="Category" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger">Delete</a>
        </span>
    </td>
</tr> 

CRMApp/Antra.CRMApp.WebMVC/Views/Shared/_CustomerRow.cshtml
@model CustomerModel
<tr>
    <td>@Model.Id</td>
    <td>@Model.Name</td>
    <td>@Model.Title</td>
    <td>@Model.Address</td>
    <td>@Model.City</td>
    <td>@Model.RegionId</td>
    <td>@Model.PostalCode</td>
    <td>@Model.Country</td>
    <td>@Model.Phone</td>
    <td>
        <span>
            <a asp-controller="Customer" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>
        </span>
    </td>
    <td>
        <span>
            <a asp-controller="Customer" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger">Delete</a>
        </span>
    </td>
</tr> 

CRMApp/Antra.CRMApp.WebMVC/Views/Shared/_EmployeeCard.cshtml
@model EmployeeResponseModel

<div class="col mb-3">
            <div class="card" style="width: 18rem;">
                <img src="@Model.PhotoPath" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">@Model.FullName</h5>
                    <p class="card-text">@Model.Address</p>
                    <a asp-action="Edit" asp-controller="Employee" asp-route-id="@Model.Id"  class="btn btn-primary">Edit</a>
                <a class="btn btn-danger" asp-action="Delete" asp-controller="Employee" asp-route-id="@Model.Id" >Delete</a>
                </div>
            </div>
            </div>

CRMApp/Antra.CRMApp.WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Antra.CRMApp.WebMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Antra.CRMApp.WebMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Antra.CRMApp.WebMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Antra.CRMApp.WebMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CRMApp/Antra.CRMApp.WebMVC/Views/Shared/_ProductRow.cshtml
@model ProductResponseModel
<tr>
    <td>@Model.Id</td>
    <td>@Model.Name</td>
    <td>@Model.VendorId</td>
    <td>@Model.CategoryId</td>
    <td>@Model.QuantityPerUnit</td>
    <td>@Model.UnitPrice</td>
    <td>@Model.UnitsInStock</td>
    <td>@Model.UnitsOnOrder</td>
    <td>@Model.ReorderLevel</td>
    <td>
        @{
            var discontinuedStatus = "Available";
            if(@Model.Discontinued)
            {
                discontinuedStatus = "Discontinued";
            }
        }
        @discontinuedStatus
    </td>
    <td>
        <span>
            <a asp-controller="Product" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>
        </span>
    </td>
    <td>
        <span>
            <a asp-controller="Product" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger">Delete</a>
        </span>
    </td>
</tr> 

CRMApp/Antra.CRMApp.WebMVC/Views/Shared/_RegionRow.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model RegionModel
<tr>
    <td>@Model.Id</td>
    <td>@Model.Name</td>
    <td>
        <span>
            <a asp-controller="Region" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>
        </span>
    </td>
    <td>
        <span>
            <a asp-controller="Region" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger">Delete</a>
        </span>
    </td>
</tr>

CRMApp/Antra.CRMApp.WebMVC/Views/Shared/_ShipperRow.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model ShipperModel
<tr>
    <td>@Model.Id</td>
    <td>@Model.Name</td>
    <td>@Model.Phone</td>
    <td>
        <span>
            <a asp-controller="Shipper" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>
        </span>
    </td>
    <td>
        <span>
            <a asp-controller="Shipper" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger">Delete</a>
        </span>
    </td>
</tr>

CRMApp/Antra.CRMApp.WebMVC/Views/Shared/_VendorRow.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model VendorResponseModel
<tr>
    <td>@Model.Id</td>
    <td>@Model.Name</td>
    <td>@Model.City</td>
    <td>@Model.Country</td>
    <td>@Model.Mobile</td>
    <td>@Model.EmailId</td>
    <td>
        @{
            var discontinuedStatus = "Unavailable";
            if(@Model.IsActive)
            {
                discontinuedStatus = "Available";
            }
        }
        @discontinuedStatus
    </td>
    <td>
        <span>
            <a asp-controller="Vendor" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>
        </span>
    </td>
    <td>
        <span>
            <a asp-controller="Vendor" asp-action="Delete"  asp-route-id="@Model.Id" class="btn btn-danger">Delete</a>
        </span>
    </td>
</tr> 

CRMApp/Antra.CRMApp.WebMVC/Views/Shared/_footer.cshtml
<footer class="border-top footer text-muted" style="position:absolute; left:0px; right:0px;bottom:0px;">
    <div class="container">
        &copy; 2022 - Antra.CRMApp.WebMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

CRMApp/Antra.CRMApp.WebMVC/Views/Shared/_header.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
 <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Antra.CRMApp.WebMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Region" asp-action="Index">Region</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>